#!/bin/bash

# script name: testAll
# description: exectutes 3 tests for designated c files- compilations, output and memory debugging
# input: list of c files to run test on


#checking for logFiles directory
if [[ -d logFiles ]]; then
	echo logFiles folder already exists 
	exit 1
fi

#creating directory and running tests
mkdir logFiles
read line < "$1"
(( l_count=0 ))
(( t_count=0 ))

while read line; do
	if [[ -z $line ]]; then
		break
	fi	
	(( l_count++ ))
	#changing delimeter for line_split
	OIFS=$IFS
	IFS='@'
	line_split=($line)
	IFS=$OIFS
	echo $l_count: ${line_split[0]}
	testCompilation logFiles/$l_count.compile.log ${line_split[1]}
	(( t_count+=$? ))
	testInOut logFiles/$l_count.inout.log ${line_split[1]} ${line_split[2]} ${line_split[3]}
	(( t_count+=$? ))
	testMemLeaks logFiles/$l_count.memory.log ${line_split[1]} ${line_split[2]}
	(( t_count+=$? ))
done < "$1"

#tests done. printing results to STDOUT
(( l_count=3*$l_count ))
(( t_count=$l_count-$t_count )) 
echo $t_count tests passed out of $l_count
exit 0
