#!/bin/bash

# script name: testCompilation
# description: compiles c file
# input: c file and name of created log file
# output: compilation log file and exe file

#cheking for # of parameters
if ((  $# != 2 )); then
  echo "need 2 parameters"
  exit 1
fi
 
gcc -g -Wall -o "$2" "$2".c 2> $1

#cheking if compilations succeeded
 

if grep -e warning: -e error: "$1" > /dev/null; then 
  echo Compile failed
  exit 1
else
  echo Compile succeeded
  exit 0 
fi  

  
